version: "3"
services:
  browser:
    image: chromedp/headless-shell
    ports:
      - "9222:9222"

  go:
    image: golang
    working_dir: /tmp/go
    entrypoint: go run example/main.go
    environment:
      - USERNAME=${USERNAME:-user}
      - PASSWORD=${PASSWORD:-pass}
    volumes:
      - ..:/tmp/go
    depends_on:
      - browser
